import React from "react";
import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./[locale]/globals.css";
import { Theme } from "@radix-ui/themes";

import Footer from "@/src/components/footer";

import { Navbar } from "../components/navbar";

const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={jost.className}>
        <Navbar />

        <Theme>{children}</Theme>
        <Footer />
      </body>
    </html>
  );
}
