import type { Metadata } from "next";
import { Inter, Jost } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./[locale]/globals.css";
import { Theme } from "@radix-ui/themes";

const inter = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={inter.className}>
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
