import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { NextIntlClientProvider, useMessages } from "next-intl";

import { Navbar } from "@/src/components/navbar";
import Footer from "@/src/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: {
    locale: string;
  };
}>) {
  const messages = useMessages();

  return (
    <section className="flex flex-col min-h-screen" lang={locale}>
      <Navbar />
      <main className="flex-grow">
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </main>
      <Footer />
    </section>
  );
}
